### REQUIRED ###

variable "project" {
  type        = string
  description = "Project name"
}

variable "contact_emails" {
  type        = list(string)
  description = "Email addresses to notify of any failures"
}

### OPTIONAL ###

variable "region" {
  type        = string
  description = "The region resources should be deployed in"
  default     = "us-east4" # Virginia
}

variable "cron_schedule" {
  description = "Cron schedule defining when to run scuba runner. Format is standard cron syntax"
  type        = string
  default     = "0 0 * * 0" # Every Sunday at midnight
}

variable "tenants_dir_path" {
  default     = "./tenants"
  type        = string
  description = "Relative path to directory containing tenant configuration files in yaml"
}

### ADVANCED ###

variable "container_image" {
  type        = string
  description = "Docker image to use for running ScubaGoggles. Must be hosted in GitHub"
  default     = "ghcr.io/cisagov/scubaconnect-gws:latest"
}

variable "container_memory_gb" {
  type        = number
  default     = 1
  description = "Number of GB of memory to allocate for the container"
}

variable "output_all_files" {
  default     = false
  type        = bool
  description = "If true, will output all files generated by ScubaGoggles instead of just the ScubaResults.json"
}

variable "input_bucket" {
  type        = string
  description = "Pre-existing bucket name to read tenant config files from containing `adhoc` and `scheduled` directories. If null, will create a bucket and upload local files"
  default     = null
}

variable "output_bucket" {
  type        = string
  description = "Pre-existing bucket name to output results to. If empty, will create a bucket"
  default     = null
}
