variable "cron_schedule" {
  description = "Cron schedule defining when to run scuba runner. Format is standard cron syntax"
  type        = string
}

variable "tenants_dir_path" {
  type        = string
  description = "Relative path to directory containing tenant configuration files in yaml"
}

variable "contact_emails" {
  type        = list(string)
  description = "Email addresses to notify of any failures"
}

### ADVANCED ###

variable "container_image" {
  type        = string
  description = "Docker image to use for running ScubaGoggles. Must be hosted in GitHub"
  default     = "ghcr.io/cisagov/scubaconnect-gws:latest"
}

variable "container_memory_gb" {
  type        = number
  default     = 1
  description = "Number of GB of memory to allocate for the container"
}

variable "output_all_files" {
  default     = false
  type        = bool
  description = "If true, will output all files generated by ScubaGoggles instead of just the ScubaResults.json"
}

variable "input_bucket" {
  type        = string
  description = "Pre-existing bucket name to read tenant config files from containing `adhoc` and `scheduled` directories. If null, will create a bucket and upload local files"
  default     = null
}

variable "create_output_bucket" {
  type        = bool
  default     = true
  description = <<-EOT
    If true, will create a local storage bucket and write results there.
    Results can be written to additional buckets via extra_output_buckets.
  EOT
}

variable "extra_output_buckets" {
  type        = list(string)
  default     = []
  description = <<-EOT
    Extra output bucket names to write results to.
    The service account must be granted storage.objects.create and storage.buckets.get 
    permissions on these buckets (e.g., via roles/storage.objectCreator).
    
    Results will be uploaded to ALL configured buckets (local + extra).
  EOT
}
