variable "resource_prefix" {
  type        = string
  description = "Prefix to use in resource names"
}

variable "application_client_id" {
  description = "The client ID of the application"
  type        = string
}

variable "application_object_id" {
  description = "Object ID of application. Only used if creating output storage; otherwise user must configure permissions"
  type        = string
}

variable "schedule_interval" {
  type        = string
  description = "The interval to run the scheduled job on."
  validation {
    condition     = contains(["Hour", "Day", "Week", "Month"], var.schedule_interval)
    error_message = "Must be one of 'Hour', 'Day', 'Week', 'Month'"
  }
}

variable "input_storage_container_url" {
  default     = null
  type        = string
  description = <<-EOT
    If not null, input container to read configs from (must assign blob reader role role to service account `sp_object_id` manually).
    Otherwise by default will create storage container. 
    Expect a container URL like: https://<account>.blob.core.windows.net/<container>
    Note that the container must have "adhoc" and "scheduled" directories. These are not created automatically in this case
  EOT
}

variable "create_output_storage" {
  type        = bool
  default     = true
  description = <<-EOT
    If true, will create a local storage container and write results there. 
    Results can be written to additional buckets via extra_output_container_urls
  EOT
}

variable "extra_output_container_urls" {
  default     = []
  type        = list(string)
  description = <<-EOT
    Extra output container URLs to write results to. URL format: https://<account>.blob.core.windows.net/<container>    
    For each container, either:
    1. Grant write permissions (Storage Blob Data Contributor) to service account `sp_object_id`, OR
    2. Provide a corresponding SAS token in extra_output_container_sas_tokens (matched by list index)
  EOT
}

variable "extra_output_container_sas_tokens" {
  default     = []
  type        = list(string)
  sensitive   = true
  description = <<-EOT
    Optional SAS tokens for extra output containers. Must match the order of extra_output_container_urls.
    Use empty string "" for containers that use service principal authentication.
  EOT

  validation {
    condition     = length(var.extra_output_container_sas_tokens) == 0 || length(var.extra_output_container_sas_tokens) == length(var.extra_output_container_urls)
    error_message = <<-EOT
      extra_output_container_sas_tokens must either be empty or have the same length as extra_output_container_urls. 
      Each SAS token corresponds to the URL at the same index. Use empty string "" for containers using service principal.
    EOT
  }
}

variable "output_all_files" {
  default     = false
  type        = bool
  description = "If true, will output all files generated by ScubaGear instead of just the ScubaResults.json"
}

variable "tenants_dir_path" {
  default     = "./tenants"
  type        = string
  description = "Relative path to directory containing tenant configuration files in yaml"
}

variable "resource_group" {
  type = object({
    name     = string
    location = string
    id       = string
  })
  description = "Resource group resources should be created in"
}

variable "contact_emails" {
  description = "Emails to notify when container has non-zero exit"
  type        = list(string)
}

variable "log_analytics_workspace" {
  type = object({
    id                 = string
    workspace_id       = string
    primary_shared_key = string
  })
  description = "Log Analytics Workspace container should write logs to"
}

variable "allowed_access_ips" {
  type        = list(string)
  description = "List of IP addresses/subnets in CIDR format that should be able to access storage"
  default     = null
}

variable "subnet_ids" {
  type        = list(string)
  description = "List of subnets used for storage and Azure Container Instances"
  default     = null
}

variable "container_registry" {
  type = object({
    server   = string
    username = string
    password = string
  })
  default     = null
  description = "Credentials for logging into registry with container image"
}

variable "container_image" {
  type        = string
  description = "Docker image to use for running ScubaGear."
}

variable "container_memory_gb" {
  type        = number
  description = "Amount of memory to allocate for ScubaGear container. Due to memory leaks in some dependencies, this may need to be increased if running on many tenants"
  default     = 3
  validation {
    condition     = var.container_memory_gb <= 16 && var.container_memory_gb >= 2
    error_message = "Container memory must be between 2GB and 16GB"
  }
}

variable "cert_info" {
  description = "Information for obtaining app certificate"
  type = object({
    vault_id   = string
    vault_name = string
    cert_name  = string
  })
}

variable "secondary_app_info" {
  description = <<-EOT
    Information for a secondary app. This can be used for one ScubaConnect instance to handle multiple environments (e.g., GCC and GCC High).
    To use, manually create an app in the other environment and add the certificate created for the primary app to it.
    Set `environment_to_use` to the environment the manual app is in, either "commericial" or "gcchigh"
  EOT
  type = object({
    app_id             = string
    environment_to_use = string
  })
  default = null
  validation {
    condition     = var.secondary_app_info == null ? true : contains(["commercial", "gcchigh"], var.secondary_app_info.environment_to_use)
    error_message = "Valid values for create_mode are (Default, PointInTimeRestore, Replica)"
  }
}
