# Purpose:  Build, sign and draft release. This workflow is a port of ScubaGear's release workflow
# This workflow's current main purpose is to sign specific PowerShell code for GearConnect
# Then create release assets

name: Build, Sign, and Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version (e.g. semver, 1.2.4)"
        required: true
        type: string

permissions: read-all

jobs:
  build-and-draft:
    name: Build and Draft Release
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        shell: powershell
    # This condition prevents duplicate runs.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Install Azure Signing Tool
        run: |
          # Source the function
          . repo/utils/workflow/Install-AzureSignTool.ps1
          Install-AzureSignTool
      # OpenID Connect (OIDC) login to Azure Public Cloud with AzPowershell
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      # Hardcoded to sign specifically named scripts in Build-SignRelease.ps1
      # We don't need to sign every script
      - name: Sign Scripts and Bundle Release Asset(s)
        run: |
          # Source the function.
          . repo/utils/workflow/Build-SignRelease.ps1
          New-ScubaReleaseAsset `
            -AzureKeyVaultUrl ${{ secrets.AZURE_KEY_VAULT_URL }} `
            -CertificateName ${{ secrets.AZURE_CERTIFICATE_NAME }} `
            -ReleaseVersion ${{ inputs.version }} `
            -RootFolderName "repo"
        # Creates release assets
      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create-release
        with:
          draft: true
          prerelease: false
          name: v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          files: |
            GearConnect-${{ inputs.version }}.zip
          generate_release_notes: true
          fail_on_unmatched_files: true